#!/bin/bash
#
# testnet-setup.sh - Set up a local Callchain testnet
#
# Usage: ./testnet-setup.sh [OPTIONS]
#
# Options:
#   -n, --nodes NUM       Number of validator nodes (default: 3)
#   -d, --dir DIR         Output directory (default: ./testnet)
#   -f, --force           Overwrite existing directory
#   -h, --help            Show this help message
#
# Example:
#   ./testnet-setup.sh --nodes 5 --dir ./my-testnet

set -e

# Configuration
NUM_NODES=3
OUTPUT_DIR="./testnet"
FORCE=0
CALLED_CMD="${CALLED_CMD:-calld}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Print usage
usage() {
    grep '^#' "$0" | tail -n +2 | sed 's/^# //'
    exit 1
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        -n|--nodes)
            NUM_NODES="$2"
            shift 2
            ;;
        -d|--dir)
            OUTPUT_DIR="$2"
            shift 2
            ;;
        -f|--force)
            FORCE=1
            shift
            ;;
        -h|--help)
            usage
            ;;
        *)
            echo "Unknown option: $1"
            usage
            ;;
    esac
done

# Validate inputs
if [[ "$NUM_NODES" -lt 1 ]] || [[ "$NUM_NODES" -gt 10 ]]; then
    echo -e "${RED}Error: Number of nodes must be between 1 and 10${NC}"
    exit 1
fi

# Check if calld is available
if ! command -v "$CALLED_CMD" &> /dev/null; then
    echo -e "${RED}Error: '$CALLED_CMD' not found in PATH${NC}"
    echo "Make sure Call-Core is built and installed:"
    echo "  cargo build --release"
    echo "  sudo cp target/release/calld /usr/local/bin/"
    exit 1
fi

# Check output directory
if [[ -d "$OUTPUT_DIR" ]]; then
    if [[ $FORCE -eq 1 ]]; then
        echo -e "${YELLOW}Removing existing directory: $OUTPUT_DIR${NC}"
        rm -rf "$OUTPUT_DIR"
    else
        echo -e "${RED}Error: Directory '$OUTPUT_DIR' already exists${NC}"
        echo "Use -f to overwrite or choose a different directory"
        exit 1
    fi
fi

echo "=========================================="
echo "  Call-Core Local Testnet Setup"
echo "=========================================="
echo ""
echo "Configuration:"
echo "  Nodes: $NUM_NODES"
echo "  Output: $OUTPUT_DIR"
echo "  Binary: $CALLED_CMD"
echo ""

# Create directory structure
mkdir -p "$OUTPUT_DIR"
for i in $(seq 1 $NUM_NODES); do
    mkdir -p "$OUTPUT_DIR/node$i"/{data,logs,config}
done

# Generate validator keys and configs
echo -e "${GREEN}Generating validator keys...${NC}"
VALIDATOR_KEYS=()
VALIDATOR_PUBKEYS=()

for i in $(seq 1 $NUM_NODES); do
    echo "  Node $i: Generating keys..."

    # Generate validation keys
    KEYS=$($CALLED_CMD validation-create 2>/dev/null)

    # Extract keys
    SEED=$(echo "$KEYS" | grep "Validation Seed:" | awk '{print $3}')
    PUBKEY=$(echo "$KEYS" | grep "Validation Public Key:" | awk '{print $4}')

    if [[ -z "$SEED" ]] || [[ -z "$PUBKEY" ]]; then
        echo -e "${RED}Error: Failed to generate keys for node $i${NC}"
        exit 1
    fi

    VALIDATOR_KEYS+=("$SEED")
    VALIDATOR_PUBKEYS+=("$PUBKEY")

    # Save keys to file
    cat > "$OUTPUT_DIR/node$i/keys.txt" << EOF
# Node $i Validator Keys
# KEEP THESE SECURE - DO NOT SHARE
Validation Seed: $SEED
Validation Public Key: $PUBKEY
EOF
    chmod 600 "$OUTPUT_DIR/node$i/keys.txt"
done

echo ""
echo -e "${GREEN}Creating configuration files...${NC}"

# Base ports
P2P_BASE_PORT=51235
RPC_BASE_PORT=5005
WS_BASE_PORT=6005

# Calculate quorum (2/3 for multi-node, 0 for single-node)
if [[ $NUM_NODES -eq 1 ]]; then
    QUORUM=0
else
    QUORUM=66
fi

for i in $(seq 1 $NUM_NODES); do
    NODE_DIR="$OUTPUT_DIR/node$i"
    P2P_PORT=$((P2P_BASE_PORT + i - 1))
    RPC_PORT=$((RPC_BASE_PORT + i - 1))
    WS_PORT=$((WS_BASE_PORT + i - 1))

    # Build bootstrap peers list (connect to all previous nodes)
    BOOTSTRAP_PEERS=""
    if [[ $i -gt 1 ]]; then
        for j in $(seq 1 $((i - 1))); do
            PEER_PORT=$((P2P_BASE_PORT + j - 1))
            if [[ -n "$BOOTSTRAP_PEERS" ]]; then
                BOOTSTRAP_PEERS="$BOOTSTRAP_PEERS, "
            fi
            BOOTSTRAP_PEERS="${BOOTSTRAP_PEERS}\"127.0.0.1:$PEER_PORT\""
        done
    fi

    # Create config file
    cat > "$NODE_DIR/call-core.toml" << EOF
# Call-Core Testnet Configuration - Node $i
# Auto-generated by testnet-setup.sh

[node]
validation_seed = "${VALIDATOR_KEYS[$((i-1))]}"
validation_public_key = "${VALIDATOR_PUBKEYS[$((i-1))]}"
database_path = "$OUTPUT_DIR/node$i/data"
log_file = "$OUTPUT_DIR/node$i/logs/node.log"
log_level = "info"
network_id = 1  # Testnet

[network]
listen_address = "127.0.0.1:$P2P_PORT"
bootstrap_peers = [$BOOTSTRAP_PEERS]
allow_inbound = true
max_peers = 10

[consensus]
validation_quorum = $QUORUM
ledger_close_time = 3

[rpc]
enabled = true
address = "127.0.0.1:$RPC_PORT"
admin_only = false

[websocket]
enabled = true
address = "127.0.0.1:$WS_PORT"
EOF

    echo "  Node $i: P2P=$P2P_PORT RPC=$RPC_PORT WS=$WS_PORT"
done

# Create genesis configuration
echo ""
echo -e "${GREEN}Creating genesis ledger...${NC}"

# Create genesis config
cat > "$OUTPUT_DIR/genesis.json" << 'EOF'
{
  "ledger_index": 1,
  "close_time": 0,
  "base_fee": 10,
  "reserve_base": 10000000,
  "reserve_inc": 2000000,
  "accounts": [
    {
      "address": "cGenesisAccount1111111111111111",
      "balance": "100000000000000000"
    }
  ]
}
EOF

# Create a master genesis account with known keys
cat > "$OUTPUT_DIR/genesis-keys.txt" << 'EOF'
# Genesis Account Keys
# These control the initial supply of CALL tokens
Address: cGenesisAccount1111111111111111
Seed: snGenesisMasterSeedForTestingOnly

WARNING: These are testnet-only keys. Do not use on mainnet.
EOF
chmod 600 "$OUTPUT_DIR/genesis-keys.txt"

# Create management scripts
echo ""
echo -e "${GREEN}Creating management scripts...${NC}"

# Create start script
cat > "$OUTPUT_DIR/start.sh" << 'SCRIPT'
#!/bin/bash
# Start the testnet

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NUM_NODES=$(ls -d "$SCRIPT_DIR"/node* 2>/dev/null | wc -l)
CALLED_CMD="${CALLED_CMD:-calld}"

echo "Starting $NUM_NODES nodes..."

for i in $(seq 1 $NUM_NODES); do
    NODE_DIR="$SCRIPT_DIR/node$i"
    if [[ -f "$NODE_DIR/call-core.toml" ]]; then
        echo "  Starting node $i..."
        cd "$NODE_DIR"
        nohup "$CALLED_CMD" --config "$NODE_DIR/call-core.toml" > "$NODE_DIR/logs/stdout.log" 2>&1 &
        echo $! > "$NODE_DIR/node.pid"
        sleep 1
    fi
done

echo "Testnet started!"
echo ""
echo "Check status with: ./status.sh"
echo "Stop with: ./stop.sh"
SCRIPT
chmod +x "$OUTPUT_DIR/start.sh"

# Create stop script
cat > "$OUTPUT_DIR/stop.sh" << 'SCRIPT'
#!/bin/bash
# Stop the testnet

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NUM_NODES=$(ls -d "$SCRIPT_DIR"/node* 2>/dev/null | wc -l)

echo "Stopping testnet..."

for i in $(seq 1 $NUM_NODES); do
    NODE_DIR="$SCRIPT_DIR/node$i"
    PIDFILE="$NODE_DIR/node.pid"

    if [[ -f "$PIDFILE" ]]; then
        PID=$(cat "$PIDFILE")
        if kill -0 "$PID" 2>/dev/null; then
            echo "  Stopping node $i (PID: $PID)..."
            kill "$PID"
            rm "$PIDFILE"
        else
            echo "  Node $i not running"
            rm -f "$PIDFILE"
        fi
    fi
done

echo "Testnet stopped."
SCRIPT
chmod +x "$OUTPUT_DIR/stop.sh"

# Create status script
cat > "$OUTPUT_DIR/status.sh" << 'SCRIPT'
#!/bin/bash
# Check testnet status

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NUM_NODES=$(ls -d "$SCRIPT_DIR"/node* 2>/dev/null | wc -l)

echo "=========================================="
echo "  Local Testnet Status"
echo "=========================================="
echo ""

for i in $(seq 1 $NUM_NODES); do
    NODE_DIR="$SCRIPT_DIR/node$i"
    PIDFILE="$NODE_DIR/node.pid"
    RPC_PORT=$((5005 + i - 1))

    echo -n "Node $i: "

    # Check if running
    if [[ -f "$PIDFILE" ]]; then
        PID=$(cat "$PIDFILE")
        if kill -0 "$PID" 2>/dev/null; then
            echo -n "Running (PID: $PID) - "

            # Check RPC
            RESPONSE=$(curl -s "http://127.0.0.1:$RPC_PORT" \
                -X POST \
                -H "Content-Type: application/json" \
                -d '{"method":"server_info"}' 2>/dev/null)

            if [[ $? -eq 0 ]]; then
                STATE=$(echo "$RESPONSE" | grep -o '"server_state":"[^"]*"' | cut -d'"' -f4)
                LEDGER=$(echo "$RESPONSE" | grep -o '"seq":[0-9]*' | cut -d':' -f2)
                echo "State: $STATE, Ledger: ${LEDGER:-unknown}"
            else
                echo "RPC not responding"
            fi
        else
            echo "Not running (stale PID file)"
        fi
    else
        echo "Not running"
    fi
done

echo ""
echo "=========================================="
SCRIPT
chmod +x "$OUTPUT_DIR/status.sh"

# Create reset script
cat > "$OUTPUT_DIR/reset.sh" << 'SCRIPT'
#!/bin/bash
# Reset testnet data (keep configs)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NUM_NODES=$(ls -d "$SCRIPT_DIR"/node* 2>/dev/null | wc -l)

echo "WARNING: This will delete all testnet data!"
read -p "Are you sure? (yes/no): " CONFIRM

if [[ "$CONFIRM" != "yes" ]]; then
    echo "Aborted."
    exit 1
fi

# Stop first
"$SCRIPT_DIR/stop.sh"

# Clear data directories
for i in $(seq 1 $NUM_NODES); do
    NODE_DIR="$SCRIPT_DIR/node$i"
    if [[ -d "$NODE_DIR/data" ]]; then
        echo "Clearing node $i data..."
        rm -rf "$NODE_DIR/data"/*
    fi
done

echo "Testnet data cleared. Start again with ./start.sh"
SCRIPT
chmod +x "$OUTPUT_DIR/reset.sh"

# Create README
cat > "$OUTPUT_DIR/README.txt" << EOF
Local Callchain Testnet
=======================

This directory contains a local testnet with $NUM_NODES validator nodes.

Quick Start:
  ./start.sh    - Start all nodes
  ./stop.sh     - Stop all nodes
  ./status.sh   - Check node status
  ./reset.sh    - Clear all data (destructive)

Node Information:

EOF

for i in $(seq 1 $NUM_NODES); do
    P2P_PORT=$((P2P_BASE_PORT + i - 1))
    RPC_PORT=$((RPC_BASE_PORT + i - 1))
    WS_PORT=$((WS_BASE_PORT + i - 1))

    cat >> "$OUTPUT_DIR/README.txt" << EOF
Node $i:
  Config: node$i/call-core.toml
  P2P:    127.0.0.1:$P2P_PORT
  RPC:    http://127.0.0.1:$RPC_PORT
  WS:     ws://127.0.0.1:$WS_PORT
  Logs:   node$i/logs/
  Keys:   node$i/keys.txt

EOF
done

cat >> "$OUTPUT_DIR/README.txt" << 'EOF'
Genesis Account:
  Address: cGenesisAccount1111111111111111
  Keys:    genesis-keys.txt

Examples:

  # Check server info
  curl http://127.0.0.1:5005 -X POST \
    -H "Content-Type: application/json" \
    -d '{"method":"server_info"}'

  # Get current ledger
  curl http://127.0.0.1:5005 -X POST \
    -H "Content-Type: application/json" \
    -d '{"method":"ledger_current"}'

  # Subscribe to ledgers via WebSocket
  wscat -c ws://127.0.0.1:6005
  > {"id":1,"command":"subscribe","streams":["ledger"]}

Documentation:
  See docs/guides/local-testnet.md for detailed instructions.
EOF

echo ""
echo "=========================================="
echo -e "${GREEN}Testnet setup complete!${NC}"
echo "=========================================="
echo ""
echo "Directory: $OUTPUT_DIR"
echo "Nodes: $NUM_NODES"
echo ""
echo "Next steps:"
echo "  cd $OUTPUT_DIR"
echo "  ./start.sh"
echo "  ./status.sh"
echo ""
echo "See README.txt for more information."
